name = "cloudflare-ticket-logger"
main = "src/index.ts"
compatibility_date = "2024-03-29"

[[d1_databases]]
binding = "DB"
database_name = "entries-local"
database_id = "e7c4a4a6-7174-4a8c-9cfc-0f57b654d039"
