name = "cloudflare-ticket-logger"
main = "./src/index.js"
compatibility_date = "2024-03-30"

# Assets binding for Pages
[assets]
directory = "./src/pages"

[[d1_databases]]
binding = "DB"
database_name = "entries-local"
database_id = "e7c4a4a6-7174-4a8c-9cfc-0f57b654d039"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "entries-production"
database_id = "e7c4a4a6-7174-4a8c-9cfc-0f57b654d039"
