ALTER TABLE entries ADD COLUMN entry_date TEXT;
ALTER TABLE entries ADD COLUMN entry_timestamp TEXT;
ALTER TABLE entries ADD COLUMN year INTEGER;
ALTER TABLE entries ADD COLUMN month INTEGER;
ALTER TABLE entries ADD COLUMN week INTEGER;
ALTER TABLE entries ADD COLUMN day INTEGER;
