name = "cloudflare-ticket-logger"
main = "src/index.js"
compatibility_date = "2024-03-30"

[[d1_databases]]
binding = "DB"
database_name = "entries-local"
database_id = "e7c4a4a6-7174-4a8c-9cfc-0f57b654d039"

# Serve static assets from the pages directory
[site]
bucket = "src/pages"
